version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: sgp-mongo-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: SGP
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:
